services:
  db:
    image: postgres:15-alpine
    container_name: odoo-db
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - ODOO_VERSION=${ODOO_VERSION}
    container_name: odoo-app
    depends_on:
      - db
    environment:
      - ODOO_VERSION=${ODOO_VERSION}
      - DB_HOST=${POSTGRES_HOST}
      - DB_PORT=${POSTGRES_PORT}
      - DB_USER=${POSTGRES_USER}
      - DB_PASSWORD=${POSTGRES_PASSWORD}
      - ODOO_ADDONS_PATH=${ODOO_ADDONS_PATH}
      - POSTGRES_DB=${POSTGRES_DB}
      - PYTHONPATH=/opt/odoo/odoo
      - DEBUGPY_ENABLE=${DEBUGPY_ENABLE:-0}
    ports:
      - "${ODOO_PORT}:8069"
      - "8072:8072"  # Puerto para longpolling
      - "5678:5678"  # Puerto para debugger
    networks:
      - odoo-network
    volumes:
      - ./addons:/opt/odoo/custom-addons
      - odoo-data:/var/lib/odoo
      - ./:/workspace:cached  # Para VS Code Remote Development
      - ./.vscode:/opt/odoo/.vscode
      - ./scripts:/opt/odoo/scripts

volumes:
  postgres_data:
  odoo-data:

networks:
  odoo-network: