services:
  db:
    image: postgres:15-alpine
    container_name: odoo-db
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - odoo-network

  odoo:
    build:
      context: .
      dockerfile: Dockerfile.odoo
    container_name: odoo-app
    depends_on:
      - db
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo
    ports:
      - "8069:8069"
    networks:
      - odoo-network

volumes:
  postgres_data:

networks:
  odoo-network: